In [1]:
import pandas as pd
import numpy as np

### Q-1)Below questions are based on this data(ncr_ride_bookings):-

In [2]:
rides = pd.read_csv("ncr_ride_bookings.csv", parse_dates = ["Date"])

In [3]:
rides.sample(2)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
142601,2024-07-03,19:38:47,"""CNR8915652""",Cancelled by Driver,"""CID1667828""",Go Sedan,Sarojini Nagar,Qutub Minar,7.5,NaN,...,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36138,2024-09-30,18:14:24,"""CNR4732720""",Completed,"""CID9578202""",Go Mini,India Gate,Tilak Nagar,5.7,17.4,...,NaN,NaN,NaN,NaN,NaN,188.0,28.3,4.3,4.4,UPI

#### 1)Convert Date and Time to datetime

In [4]:
rides["Date"].dtype # we had converted the date col to date col to datetime dtype at time of reading csv file

dtype('<M8[ns]')

In [5]:
rides["Time"] = pd.to_datetime(rides["Time"], errors = "coerce", format = "%H:%M:%S") 
## pandas add dummy date to time 1900-01-01 hh:mm:ss
# if we don't want this dummy date then do this:
# pd.to_datetime(rides["Time"], errors = "coerce", format = "%H:%M:%S").dt.time .
# However, this will be python datetime obj and will be of "object type".

In [6]:
rides["Time"].dtype

dtype('<M8[ns]')

In [7]:
rides.sample()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
113509,2024-07-01,1900-01-01 17:58:32,"""CNR7565762""",Cancelled by Customer,"""CID9699171""",Uber XL,Huda City Centre,Ghitorni Village,8.3,NaN,...,Wrong Address,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 2)Combine Date and Time into a single datetime column
##### method 1:

Since our "Date" and "Time" are both datetime, we can’t directly add them.
But if we convert each to string in the right format using .dt.strftime(),
then concatenate, then parse back → we get a clean datetime column:

##### method 2:
we could also combine these two cols durind reading the file time only using parde_date = [" "] and get datetime type col

##### some situation:

if: 

"Date" is datetime64[ns]

"Time" (after pd.to_datetime(rides["Time"], errors = "coerce", format = "%H:%M:%S").dt.time .) is Python datetime.time objects (object dtype)

Pandas can’t directly add those two.

solution: 

rides["Date Time"] = pd.to_datetime( rides["Date"].astype(str) + " " + rides["Time"].astype(str),errors="coerce")

In [8]:
#method 1:

rides["Date Time"] = pd.to_datetime(rides["Date"].dt.strftime("%Y-%m-%d")+" "+ rides["Time"].dt.strftime("%H-%M-%S"), format = "%Y-%m-%d %H-%M-%S",errors = "coerce")

In [9]:
rides["Date Time"].dtype

dtype('<M8[ns]')

In [10]:
rides.sample(3)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Date Time
22753,2024-01-01,1900-01-01 09:31:14,"""CNR1819661""",Cancelled by Customer,"""CID3789290""",Go Mini,Dwarka Sector 21,DLF City Court,18.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01 09:31:14
51231,2024-04-24,1900-01-01 12:18:25,"""CNR9673697""",Completed,"""CID7010329""",Auto,Subhash Nagar,Tagore Garden,6.1,35.7,...,NaN,NaN,NaN,NaN,728.0,48.82,4.3,4.8,UPI,2024-04-24 12:18:25
42720,2024-08-25,1900-01-01 20:14:02,"""CNR6059633""",Completed,"""CID9314196""",Uber XL,Welcome,Lal Quila,6.4,42.1,...,NaN,NaN,NaN,NaN,182.0,11.06,4.3,4.5,UPI,2024-08-25 20:14:02

In [11]:
#method 2:
#will be deprecated in future . so use above method
rides2 = pd.read_csv("ncr_ride_bookings.csv", parse_dates = {"DateTime" : ["Date","Time"]})

C:\Users\Hp\AppData\Local\Temp\ipykernel_23280\1027789386.py:3: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  rides2 = pd.read_csv("ncr_ride_bookings.csv", parse_dates = {"DateTime" : ["Date","Time"]})

In [12]:
rides2

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23 12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29 18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23 08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21 17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16 22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11 19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,NaN,NaN,NaN,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24 15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,NaN,NaN,NaN,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18 10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,NaN,NaN,NaN,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05 07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,NaN,NaN,NaN,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI
149999,2024-03-10 15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,NaN,NaN,NaN,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card

#### 3)Extract temporal features

In [13]:
rides["Date Time"].dt.year

0         2024
1         2024
2         2024
3         2024
4         2024
          ...
149995    2024
149996    2024
149997    2024
149998    2024
149999    2024
Name: Date Time, Length: 150000, dtype: int32

In [14]:
rides["Date Time"].dt.month

0          3
1         11
2          8
3         10
4          9
          ..
149995    11
149996    11
149997     9
149998    10
149999     3
Name: Date Time, Length: 150000, dtype: int32

In [15]:
rides["Date Time"].dt.day

0         23
1         29
2         23
3         21
4         16
          ..
149995    11
149996    24
149997    18
149998     5
149999    10
Name: Date Time, Length: 150000, dtype: int32

In [16]:
rides["Date Time"].dt.day_name()

0          Saturday
1            Friday
2            Friday
3            Monday
4            Monday
            ...
149995       Monday
149996       Sunday
149997    Wednesday
149998     Saturday
149999       Sunday
Name: Date Time, Length: 150000, dtype: object

In [17]:
rides["Date Time"].dt.month_name()

0             March
1          November
2            August
3           October
4         September
            ...
149995     November
149996     November
149997    September
149998      October
149999        March
Name: Date Time, Length: 150000, dtype: object

In [18]:
rides["Date Time"].dt.hour

0         12
1         18
2          8
3         17
4         22
          ..
149995    19
149996    15
149997    10
149998     7
149999    15
Name: Date Time, Length: 150000, dtype: int32

In [19]:
rides["Date Time"].dt.minute

0         29
1          1
2         56
3         17
4          8
          ..
149995    34
149996    55
149997    55
149998    53
149999    38
Name: Date Time, Length: 150000, dtype: int32

In [20]:
rides["Date Time"].dt.second

0         38
1         39
2         10
3         25
4          0
          ..
149995     1
149996     9
149997    15
149998    34
149999     3
Name: Date Time, Length: 150000, dtype: int32

In [21]:
rides["Date Time"].dt.day_of_week

0         5
1         4
2         4
3         0
4         0
         ..
149995    0
149996    6
149997    2
149998    5
149999    6
Name: Date Time, Length: 150000, dtype: int32

#### # 4)Create binary flags from cancellation/incomplete columns

In [22]:

pd.set_option("display.max_column",None)
rides2.sample(3)

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
88618,2024-10-23 01:48:57,"""CNR8499430""",Completed,"""CID8781785""",Auto,Mansarovar Park,Nirman Vihar,3.8,17.1,NaN,NaN,NaN,NaN,NaN,NaN,413.0,30.72,4.6,4.2,Credit Card
40958,2024-10-03 07:43:39,"""CNR5990809""",Completed,"""CID5944105""",Premier Sedan,Rohini,Old Gurgaon,3.0,40.3,NaN,NaN,NaN,NaN,NaN,NaN,64.0,10.64,3.8,3.0,Credit Card
104763,2024-02-15 16:23:11,"""CNR3510067""",Completed,"""CID7682529""",Auto,Jasola,Pataudi Chowk,3.0,30.3,NaN,NaN,NaN,NaN,NaN,NaN,863.0,11.18,5.0,3.7,Uber Wallet

In [23]:
rides2["cancellation_flag"] = np.where((rides2["Cancelled Rides by Customer"].notna() ) | (rides2["Cancelled Rides by Driver"].notna() ),1,0)

In [24]:
rides2["cancellation_flag"].value_counts()  ## 1: ride cancelled, 0 : not cancelled

cancellation_flag
0    112500
1     37500
Name: count, dtype: int64

In [25]:
rides2["customer_cancellation_flag"] = np.where(rides2["Cancelled Rides by Customer"].notna(),1,0)

In [26]:
rides2["customer_cancellation_flag"].value_counts()

customer_cancellation_flag
0    139500
1     10500
Name: count, dtype: int64

In [27]:
rides2["driver_cancellation_flag"] = np.where(rides2["Cancelled Rides by Driver"].notna(),1,0)

In [28]:
rides2["driver_cancellation_flag"].value_counts()

driver_cancellation_flag
0    123000
1     27000
Name: count, dtype: int64

In [29]:
rides2["incomplete_flag"] = np.where(rides2["Incomplete Rides"].notna(), 1,0)

In [30]:
rides2["incomplete_flag"].value_counts()

incomplete_flag
0    141000
1      9000
Name: count, dtype: int64

#### 5)Create a flag for missing ratings and booking values

In [31]:
rides2.sample(3)

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag
79441,2024-05-11 21:54:05,"""CNR1332360""",Completed,"""CID5117958""",eBike,Paharganj,Sarojini Nagar,5.3,26.2,NaN,NaN,NaN,NaN,NaN,NaN,501.0,31.78,3.7,4.6,Uber Wallet,0,0,0,0
107434,2024-03-30 11:10:36,"""CNR3300848""",Cancelled by Customer,"""CID6151068""",Uber XL,Saket A Block,India Gate,7.2,NaN,1.0,Wrong Address,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,0
143530,2024-08-25 07:44:16,"""CNR2879203""",Completed,"""CID2074718""",eBike,Green Park,Rithala,9.3,30.2,NaN,NaN,NaN,NaN,NaN,NaN,209.0,48.66,4.9,4.7,Credit Card,0,0,0,0

In [32]:
rides2["missing_ratings"] = np.where((rides2["Driver Ratings"].notna()) & (rides2["Customer Rating"].notna()),0,1)

In [33]:
rides2["driver_missing_ratings"]  = np.where(rides["Driver Ratings"].notna(),0,1)

In [34]:
rides2["customer_missing_ratings"]  = np.where(rides["Customer Rating"].notna(),0,1)

In [35]:
rides2.sample(3)

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag,missing_ratings,driver_missing_ratings,customer_missing_ratings
107349,2024-02-22 07:01:24,"""CNR4873166""",Completed,"""CID1850073""",Go Mini,RK Puram,Ashram,5.1,17.7,NaN,NaN,NaN,NaN,NaN,NaN,260.0,3.47,4.7,4.9,UPI,0,0,0,0,0,0,0
39899,2024-10-09 21:53:40,"""CNR8429039""",Completed,"""CID4419320""",Go Sedan,AIIMS,Netaji Subhash Place,5.0,37.2,NaN,NaN,NaN,NaN,NaN,NaN,451.0,9.54,4.3,4.8,UPI,0,0,0,0,0,0,0
102115,2024-09-25 12:58:17,"""CNR9902985""",Completed,"""CID3149176""",eBike,Sushant Lok,Hero Honda Chowk,7.2,34.0,NaN,NaN,NaN,NaN,NaN,NaN,282.0,38.87,4.3,4.2,UPI,0,0,0,0,0,0,0

In [36]:
rides2["Booking Value"]  = np.where(rides["Booking Value"].notna(),0,1)

In [37]:
rides2["Booking Value"].value_counts()

Booking Value
0    102000
1     48000
Name: count, dtype: int64

#### 6)Define Target for Customer Cancellation

In [38]:
# we have already created the target which is customer cancellation flg
rides2["customer_cancellation_flag"].value_counts()

customer_cancellation_flag
0    139500
1     10500
Name: count, dtype: int64

#### 7)Cancellation Rate by Vehicle Type

In [39]:
# method 1
round((rides2.groupby("Vehicle Type")["cancellation_flag"].mean())*100,2).reset_index()

    Vehicle Type  cancellation_flag
0           Auto              24.92
1           Bike              25.10
2        Go Mini              24.92
3       Go Sedan              25.29
4  Premier Sedan              24.94
5        Uber XL              24.48
6          eBike              24.91

In [40]:
# method 2
round((rides2.groupby("Vehicle Type").agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

               cancellation_rate
Vehicle Type
Auto                       24.92
Bike                       25.10
Go Mini                    24.92
Go Sedan                   25.29
Premier Sedan              24.94
Uber XL                    24.48
eBike                      24.91

##### why use mean for cancellation rate: 
Suppose in the 10 AM group you have 5 rides:

Sum of flags = 1+0+0+1+0 = 2

Total rides = 5

Cancellation rate = 2/5 = 0.4 (40%)

Now check what mean gives:

mean=(1+0+0+1+0)/5=0.4

Same thing!

#### 8)Cancellation Rate by Hour

In [41]:
rides2.sample()

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag,missing_ratings,driver_missing_ratings,customer_missing_ratings
15501,2024-08-04 18:22:58,"""CNR4063756""",Completed,"""CID1664740""",eBike,Welcome,Lajpat Nagar,9.0,18.3,NaN,NaN,NaN,NaN,NaN,NaN,0,27.08,4.4,4.3,Debit Card,0,0,0,0,0,0,0

In [42]:
# rides2["hours"]=rides2["DateTime"].dt.hour

In [43]:
round((rides2.groupby(rides2["DateTime"].dt.hour).agg( cancellation_rate_by_hour = ("cancellation_flag" ,"mean")))*100,2)

          cancellation_rate_by_hour
DateTime
0                             24.76
1                             25.29
2                             22.18
3                             25.67
4                             25.59
5                             26.42
6                             24.16
7                             25.36
8                             24.98
9                             24.91
10                            24.90
11                            24.05
12                            24.74
13                            25.25
14                            26.08
15                            25.68
16                            24.52
17                            24.89
18                            25.38
19                            25.53
20                            24.59
21                            23.98
22                            25.57
23                            25.42

#### 9)Cancellation Rate by Day of Week

In [44]:
days = ["Monday","Tuesday","Wednesday","Thursday","Friday", "Saturday","Sunday"]
cancellation_by_day = round((rides2.groupby(rides2["DateTime"].dt.day_name()).agg(cancellation_rate_day = ("cancellation_flag" ,"mean")))*100,2)
cancellation_by_day.reindex(days)

           cancellation_rate_day
DateTime
Monday                     25.65
Tuesday                    25.19
Wednesday                  24.82
Thursday                   24.66
Friday                     24.97
Saturday                   24.73
Sunday                     24.97

#### 10)Driver Rating vs Cancellation

In [45]:
round((rides2.groupby(rides2["Driver Ratings"]).agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

                cancellation_rate
Driver Ratings
3.0                           0.0
3.1                           0.0
3.2                           0.0
3.3                           0.0
3.4                           0.0
3.5                           0.0
3.6                           0.0
3.7                           0.0
3.8                           0.0
3.9                           0.0
4.0                           0.0
4.1                           0.0
4.2                           0.0
4.3                           0.0
4.4                           0.0
4.5                           0.0
4.6                           0.0
4.7                           0.0
4.8                           0.0
4.9                           0.0
5.0                           0.0

In [46]:
# making bins of ratings
bins = [0,2,3,4,5]
labels = ["1-2","2-3","3-4","4-5"]
rides2["ratings"]=pd.cut(rides2["Driver Ratings"], bins = bins , labels = labels, include_lowest = True)

In [47]:
round((rides2.groupby(rides2["ratings"]).agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

C:\Users\Hp\AppData\Local\Temp\ipykernel_23280\3030147022.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  round((rides2.groupby(rides2["ratings"]).agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

         cancellation_rate
ratings
1-2                    NaN
2-3                    0.0
3-4                    0.0
4-5                    0.0

#### 11)Top 10 Pickup Locations by Count

In [48]:
rides2.sample()

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag,missing_ratings,driver_missing_ratings,customer_missing_ratings,ratings
16515,2024-10-03 21:51:08,"""CNR2762553""",Cancelled by Driver,"""CID1922492""",Premier Sedan,Jama Masjid,Kanhaiya Nagar,7.3,NaN,NaN,NaN,1.0,Personal & Car related issues,NaN,NaN,1,NaN,NaN,NaN,NaN,1,0,1,0,1,1,1,NaN

In [49]:
rides2["Pickup Location"].value_counts().sort_values().tail(10)

Pickup Location
Pataudi Chowk       907
Dwarka Sector 21    914
Mehrauli            915
AIIMS               918
Madipur             919
Pragati Maidan      920
Badarpur            921
Saket               931
Barakhamba Road     946
Khandsa             949
Name: count, dtype: int64

#### 12)Trend of Cancellations Over Time (Daily)

### Q-2)Below questions are based on this data(Weather Data):-

In [50]:
weather = pd.read_csv("Weather Data.csv")

In [51]:
weather.sample(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
5727,8/26/2012 15:00,30.1,15.7,42,13,48.3,101.76,Mainly Clear
2958,5/3/2012 6:00,11.4,8.5,82,13,24.1,101.31,Cloudy

#### 1)Print Column Name & Unique Values

In [52]:
# method 1:
for i in weather :
    print(np.unique(weather[i].values))

['1/1/2012 0:00' '1/1/2012 10:00' '1/1/2012 11:00' ... '9/9/2012 7:00'
 '9/9/2012 8:00' '9/9/2012 9:00']
[-23.3 -23.2 -22.8 -22.2 -21.4 -21.3 -21.2 -21.1 -21.  -20.7 -20.6 -20.3
 -20.  -19.9 -19.6 -19.5 -19.3 -19.2 -19.1 -19.  -18.7 -18.6 -18.5 -18.4
 -18.3 -18.2 -18.1 -18.  -17.9 -17.8 -17.7 -17.6 -17.5 -17.4 -17.3 -17.2
 -17.1 -17.  -16.9 -16.8 -16.7 -16.6 -16.4 -16.3 -16.2 -16.1 -16.  -15.9
 -15.8 -15.7 -15.5 -15.4 -15.3 -15.2 -15.1 -15.  -14.9 -14.8 -14.7 -14.6
 -14.5 -14.4 -14.3 -14.2 -14.  -13.9 -13.8 -13.7 -13.6 -13.5 -13.4 -13.3
 -13.2 -13.1 -13.  -12.9 -12.8 -12.7 -12.6 -12.5 -12.4 -12.3 -12.2 -12.1
 -12.  -11.9 -11.8 -11.7 -11.6 -11.5 -11.4 -11.3 -11.2 -11.1 -11.  -10.9
 -10.8 -10.7 -10.6 -10.5 -10.4 -10.3 -10.2 -10.1 -10.   -9.9  -9.8  -9.7
  -9.6  -9.5  -9.4  -9.3  -9.2  -9.1  -9.   -8.9  -8.8  -8.7  -8.6  -8.5
  -8.4  -8.3  -8.2  -8.1  -8.   -7.9  -7.8  -7.7  -7.6  -7.5  -7.4  -7.3
  -7.2  -7.1  -7.   -6.9  -6.8  -6.7  -6.6  -6.5  -6.4  -6.3  -6.2  -6.1
  -6.   -5.9  -5.8  -5.7  -5.6  -5.5  -5.4  -5.3  -5.2  -5.1  -5.   -4.9
  -4.8  -4.7  -4.6  -4.5  -4.4  -4.3  -4.2  -4.1  -4.   -3.9  -3.8  -3.7
  -3.6  -3.5  -3.4  -3.3  -3.2  -3.1  -3.   -2.9  -2.8  -2.7  -2.6  -2.5
  -2.4  -2.3  -2.2  -2.1  -2.   -1.9  -1.8  -1.7  -1.6  -1.5  -1.4  -1.3
  -1.2  -1.1  -1.   -0.9  -0.8  -0.7  -0.6  -0.5  -0.4  -0.3  -0.2  -0.1
   0.    0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9   1.    1.1
   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1   2.2   2.3
   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3   3.4   3.5
   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5   4.6   4.7
   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9
   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1
   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3
   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5
   9.6   9.7   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5  10.6  10.7
  10.8  10.9  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7  11.8  11.9
  12.   12.1  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9  13.   13.1
  13.2  13.3  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1  14.2  14.3
  14.4  14.5  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3  15.4  15.5
  15.6  15.7  15.8  15.9  16.   16.1  16.2  16.3  16.4  16.5  16.6  16.7
  16.8  16.9  17.   17.1  17.2  17.3  17.4  17.5  17.6  17.7  17.8  17.9
  18.   18.1  18.2  18.3  18.4  18.5  18.6  18.7  18.8  18.9  19.   19.1
  19.2  19.3  19.4  19.5  19.6  19.7  19.8  19.9  20.   20.1  20.2  20.3
  20.4  20.5  20.6  20.7  20.8  20.9  21.   21.1  21.2  21.3  21.4  21.5
  21.6  21.7  21.8  21.9  22.   22.1  22.2  22.3  22.4  22.5  22.6  22.7
  22.8  22.9  23.   23.1  23.2  23.3  23.4  23.5  23.6  23.7  23.8  23.9
  24.   24.1  24.2  24.3  24.4  24.5  24.6  24.7  24.8  24.9  25.   25.1
  25.2  25.3  25.4  25.5  25.6  25.7  25.8  25.9  26.   26.1  26.2  26.3
  26.4  26.5  26.6  26.7  26.8  26.9  27.   27.1  27.2  27.3  27.4  27.5
  27.6  27.7  27.8  27.9  28.   28.1  28.2  28.3  28.4  28.5  28.6  28.7
  28.8  28.9  29.   29.1  29.2  29.3  29.4  29.5  29.6  29.7  29.8  29.9
  30.   30.1  30.2  30.3  30.4  30.5  30.6  30.7  30.8  30.9  31.1  31.2
  31.4  31.5  31.6  31.7  31.8  31.9  32.   32.1  32.2  32.3  32.4  32.5
  32.6  32.7  32.8  32.9  33. ]
[-28.5 -28.  -27.8 -26.8 -26.6 -26.5 -26.2 -26.1 -26.  -25.9 -25.8 -25.6
 -25.5 -25.4 -25.3 -25.1 -24.8 -24.6 -24.5 -24.4 -24.3 -24.2 -24.1 -24.
 -23.9 -23.8 -23.7 -23.6 -23.5 -23.4 -23.3 -23.2 -23.1 -23.  -22.9 -22.8
 -22.7 -22.6 -22.5 -22.4 -22.3 -22.2 -22.1 -22.  -21.9 -21.8 -21.7 -21.6
 -21.5 -21.4 -21.3 -21.2 -21.1 -21.  -20.9 -20.8 -20.7 -20.6 -20.5 -20.4
 -20.3 -20.2 -20.1 -20.  -19.9 -19.8 -19.7 -19.6 -19.5 -19.4 -19.3 -19.2
 -19.1 -19.  -18.9 -18.8 -18.7 -18.6 -18.5 -18.4 -18.3 -18.2 -18.1 -18.
 -17.9 -17.8 -17.7 -17.6 -17.5 -17.4 -17.3 -17.2 -17.1 -17.  -16.9 -16.8
 -16.7 -16.6 -16.5 -16.4 -16.3 -16.2 -16.1 -16.  -15.9 -15.8 -15.7 -15.6
 -15.5 -15.4 -15.3 -15.2 -15.1 -15.  -14.9 -14.8 -14.7 -14.6 -14.5 -14.4
 -14.3 -14.2 -14.1 -14.  -13.9 -13.8 -13.7 -13.6 -13.5 -13.4 -13.3 -13.2
 -13.1 -13.  -12.9 -12.8 -12.7 -12.6 -12.5 -12.4 -12.3 -12.2 -12.1 -12.
 -11.9 -11.8 -11.7 -11.6 -11.5 -11.4 -11.3 -11.2 -11.1 -11.  -10.9 -10.8
 -10.7 -10.6 -10.5 -10.4 -10.3 -10.2 -10.1 -10.   -9.9  -9.8  -9.7  -9.6
  -9.5  -9.4  -9.3  -9.2  -9.1  -9.   -8.9  -8.8  -8.7  -8.6  -8.5  -8.4
  -8.3  -8.2  -8.1  -8.   -7.9  -7.8  -7.7  -7.6  -7.5  -7.4  -7.3  -7.2
  -7.1  -7.   -6.9  -6.8  -6.7  -6.6  -6.5  -6.4  -6.3  -6.2  -6.1  -6.
  -5.9  -5.8  -5.7  -5.6  -5.5  -5.4  -5.3  -5.2  -5.1  -5.   -4.9  -4.8
  -4.7  -4.6  -4.5  -4.4  -4.3  -4.2  -4.1  -4.   -3.9  -3.8  -3.7  -3.6
  -3.5  -3.4  -3.3  -3.2  -3.1  -3.   -2.9  -2.8  -2.7  -2.6  -2.5  -2.4
  -2.3  -2.2  -2.1  -2.   -1.9  -1.8  -1.7  -1.6  -1.5  -1.4  -1.3  -1.2
  -1.1  -1.   -0.9  -0.8  -0.7  -0.6  -0.5  -0.4  -0.3  -0.2  -0.1   0.
   0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9   1.    1.1   1.2
   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1   2.2   2.3   2.4
   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3   3.4   3.5   3.6
   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5   4.6   4.7   4.8
   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9   6.
   6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1   7.2
   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3   8.4
   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5   9.6
   9.7   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5  10.6  10.7  10.8
  10.9  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7  11.8  11.9  12.
  12.1  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9  13.   13.1  13.2
  13.3  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1  14.2  14.3  14.4
  14.5  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3  15.4  15.5  15.6
  15.7  15.8  15.9  16.   16.1  16.2  16.3  16.4  16.5  16.6  16.7  16.8
  16.9  17.   17.1  17.2  17.3  17.4  17.5  17.6  17.7  17.8  17.9  18.
  18.1  18.2  18.3  18.4  18.5  18.6  18.7  18.8  18.9  19.   19.1  19.2
  19.3  19.4  19.5  19.6  19.7  19.8  19.9  20.   20.1  20.2  20.3  20.4
  20.5  20.6  20.7  20.8  20.9  21.   21.1  21.2  21.3  21.7  21.8  21.9
  22.   22.2  22.3  22.6  22.9  23.   23.1  23.2  24.4]
[ 18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
[ 0  2  4  6  7  9 11 13 15 17 19 20 22 24 26 28 30 32 33 35 37 39 41 43
 44 46 48 50 52 54 57 63 70 83]
[ 0.2  0.4  0.6  0.8  1.   1.2  1.6  2.   2.4  2.8  3.2  3.6  4.   4.8
  6.4  8.   9.7 11.3 12.9 16.1 19.3 24.1 25.  48.3]
[ 97.52  97.56  97.58  97.64  97.75  97.76  97.79  97.81  97.84  97.89
  97.93  97.97  97.98  97.99  98.    98.03  98.06  98.07  98.1   98.11
  98.16  98.18  98.19  98.2   98.22  98.23  98.29  98.31  98.32  98.33
  98.36  98.39  98.44  98.45  98.47  98.5   98.51  98.53  98.54  98.55
  98.56  98.58  98.6   98.61  98.62  98.63  98.64  98.65  98.66  98.67
  98.68  98.69  98.7   98.71  98.72  98.73  98.74  98.75  98.76  98.78
  98.79  98.8   98.81  98.82  98.84  98.86  98.88  98.89  98.9   98.91
  98.92  98.94  98.96  98.97  98.98  99.    99.01  99.02  99.05  99.06
  99.07  99.08  99.09  99.1   99.11  99.12  99.13  99.14  99.15  99.16
  99.17  99.18  99.19  99.2   99.21  99.22  99.23  99.24  99.25  99.26
  99.27  99.28  99.29  99.3   99.31  99.32  99.33  99.34  99.35  99.36
  99.37  99.38  99.39  99.4   99.41  99.42  99.43  99.44  99.45  99.46
  99.47  99.48  99.49  99.5   99.51  99.52  99.53  99.54  99.55  99.56
  99.57  99.58  99.59  99.6   99.61  99.62  99.63  99.64  99.65  99.66
  99.67  99.68  99.69  99.7   99.71  99.72  99.73  99.74  99.75  99.76
  99.77  99.78  99.79  99.8   99.81  99.82  99.83  99.84  99.85  99.86
  99.87  99.88  99.89  99.9   99.91  99.92  99.93  99.94  99.95  99.96
  99.97  99.98  99.99 100.   100.01 100.02 100.03 100.04 100.05 100.06
 100.07 100.08 100.09 100.1  100.11 100.12 100.13 100.14 100.15 100.16
 100.17 100.18 100.19 100.2  100.21 100.22 100.23 100.24 100.25 100.26
 100.27 100.28 100.29 100.3  100.31 100.32 100.33 100.34 100.35 100.36
 100.37 100.38 100.39 100.4  100.41 100.42 100.43 100.44 100.45 100.46
 100.47 100.48 100.49 100.5  100.51 100.52 100.53 100.54 100.55 100.56
 100.57 100.58 100.59 100.6  100.61 100.62 100.63 100.64 100.65 100.66
 100.67 100.68 100.69 100.7  100.71 100.72 100.73 100.74 100.75 100.76
 100.77 100.78 100.79 100.8  100.81 100.82 100.83 100.84 100.85 100.86
 100.87 100.88 100.89 100.9  100.91 100.92 100.93 100.94 100.95 100.96
 100.97 100.98 100.99 101.   101.01 101.02 101.03 101.04 101.05 101.06
 101.07 101.08 101.09 101.1  101.11 101.12 101.13 101.14 101.15 101.16
 101.17 101.18 101.19 101.2  101.21 101.22 101.23 101.24 101.25 101.26
 101.27 101.28 101.29 101.3  101.31 101.32 101.33 101.34 101.35 101.36
 101.37 101.38 101.39 101.4  101.41 101.42 101.43 101.44 101.45 101.46
 101.47 101.48 101.49 101.5  101.51 101.52 101.53 101.54 101.55 101.56
 101.57 101.58 101.59 101.6  101.61 101.62 101.63 101.64 101.65 101.66
 101.67 101.68 101.69 101.7  101.71 101.72 101.73 101.74 101.75 101.76
 101.77 101.78 101.79 101.8  101.81 101.82 101.83 101.84 101.85 101.86
 101.87 101.88 101.89 101.9  101.91 101.92 101.93 101.94 101.95 101.96
 101.97 101.98 101.99 102.   102.01 102.02 102.03 102.04 102.05 102.06
 102.07 102.08 102.09 102.1  102.11 102.12 102.13 102.14 102.15 102.16
 102.17 102.18 102.19 102.2  102.21 102.22 102.23 102.24 102.25 102.26
 102.27 102.28 102.29 102.3  102.31 102.32 102.33 102.34 102.35 102.36
 102.37 102.38 102.39 102.4  102.41 102.42 102.43 102.44 102.45 102.46
 102.47 102.48 102.49 102.5  102.51 102.52 102.53 102.54 102.55 102.56
 102.57 102.58 102.59 102.6  102.61 102.62 102.63 102.64 102.65 102.66
 102.67 102.68 102.69 102.7  102.71 102.72 102.73 102.74 102.75 102.78
 102.79 102.81 102.82 102.83 102.84 102.85 102.86 102.89 102.9  102.91
 102.92 102.93 102.94 102.95 102.96 102.97 102.98 102.99 103.   103.01
 103.02 103.03 103.04 103.05 103.06 103.07 103.08 103.09 103.1  103.11
 103.12 103.13 103.14 103.15 103.16 103.17 103.18 103.19 103.2  103.21
 103.22 103.23 103.24 103.25 103.26 103.27 103.28 103.29 103.3  103.31
 103.34 103.36 103.38 103.39 103.43 103.46 103.47 103.49 103.5  103.51
 103.52 103.54 103.56 103.58 103.59 103.61 103.63 103.65]
['Clear' 'Cloudy' 'Drizzle' 'Drizzle,Fog' 'Drizzle,Ice Pellets,Fog'
 'Drizzle,Snow' 'Drizzle,Snow,Fog' 'Fog' 'Freezing Drizzle'
 'Freezing Drizzle,Fog' 'Freezing Drizzle,Haze' 'Freezing Drizzle,Snow'
 'Freezing Fog' 'Freezing Rain' 'Freezing Rain,Fog' 'Freezing Rain,Haze'
 'Freezing Rain,Ice Pellets,Fog' 'Freezing Rain,Snow Grains' 'Haze'
 'Mainly Clear' 'Moderate Rain,Fog' 'Moderate Snow'
 'Moderate Snow,Blowing Snow' 'Mostly Cloudy' 'Rain' 'Rain Showers'
 'Rain Showers,Fog' 'Rain Showers,Snow Showers' 'Rain,Fog' 'Rain,Haze'
 'Rain,Ice Pellets' 'Rain,Snow' 'Rain,Snow Grains' 'Rain,Snow,Fog'
 'Rain,Snow,Ice Pellets' 'Snow' 'Snow Pellets' 'Snow Showers'
 'Snow Showers,Fog' 'Snow,Blowing Snow' 'Snow,Fog' 'Snow,Haze'
 'Snow,Ice Pellets' 'Thunderstorms' 'Thunderstorms,Heavy Rain Showers'
 'Thunderstorms,Moderate Rain Showers,Fog' 'Thunderstorms,Rain'
 'Thunderstorms,Rain Showers' 'Thunderstorms,Rain Showers,Fog'
 'Thunderstorms,Rain,Fog']

In [53]:
# method 2:
for col in weather.columns:
    print(col, ":", weather[col].unique())

Date/Time : ['1/1/2012 0:00' '1/1/2012 1:00' '1/1/2012 2:00' ... '12/31/2012 21:00'
 '12/31/2012 22:00' '12/31/2012 23:00']
Temp_C : [ -1.8  -1.5  -1.4  -1.3  -1.   -0.5  -0.2   0.2   0.8   1.8   2.6   3.
   3.8   3.1   3.2   4.    4.4   5.3   5.2   4.6   3.9   3.7   2.9   2.3
   2.    1.9   1.5   2.2   1.7   1.1   0.   -0.7  -2.1  -4.1  -4.8  -5.6
  -5.8  -7.   -7.4  -9.   -9.7 -10.5 -11.3 -12.6 -12.9 -13.3 -14.  -14.8
 -15.  -15.3 -14.9 -15.1 -15.8 -16.3 -16.9 -17.3 -17.  -17.1 -17.5 -17.9
 -18.1 -18.5 -18.6 -18.2 -17.8 -16.8 -15.2 -14.2 -13.7 -12.4 -10.2  -9.4
  -8.9  -8.4  -7.8  -7.6  -9.5  -9.6  -8.8  -7.5  -5.4  -5.   -8.2  -7.1
  -6.1  -6.6  -6.   -4.7  -4.4  -5.1  -4.3  -6.7  -9.2  -9.8  -9.9 -10.
 -10.6 -11.8 -12.  -14.4 -12.3 -12.5 -11.7 -11.9 -11.2 -11.5 -11.6  -9.3
  -8.7  -8.5  -8.1  -6.9  -6.4  -5.7  -5.5  -3.7  -3.6  -3.1  -3.2  -3.
   0.4   0.6  -0.6  -1.7  -3.5  -5.9  -6.5  -7.2  -8.   -8.3  -7.7  -6.8
  -2.5  -1.1  -0.3   2.5   1.4   1.6   1.2   0.7  -4.   -4.9  -7.3  -8.6
 -10.7 -12.7 -13.4 -13.9 -14.7 -14.3 -12.2 -11.4 -10.8  -6.2  -5.2  -4.6
  -4.5  -2.9 -18.  -16.7 -17.4 -17.7 -18.3 -19.6 -20.  -19.9 -20.3 -21.2
 -21.1 -21.4 -20.7 -21.  -21.3 -23.2 -22.8 -23.3 -22.2 -20.6 -19.3 -16.
 -15.4 -16.2 -19.2 -18.7 -19.1 -13.6 -10.1 -10.4  -5.3  -3.3  -1.6   2.1
   0.5 -10.9 -11.1 -11.  -10.3 -16.6 -14.6  -4.2  -3.9  -6.3 -15.5 -15.9
 -16.4 -16.1 -12.1 -13.  -17.6 -18.4 -17.2 -19.5 -19.  -14.5 -13.2   2.7
   3.3   3.6   3.5   5.    4.2   3.4   2.8   2.4   1.3   1.   -0.1  -0.4
  -2.8  -7.9  -3.4  -3.8  -0.8   0.3   0.1  -1.2   0.9  -0.9  -2.   -1.9
  -2.2  -2.3 -15.7 -13.5 -13.8  -2.4 -13.1 -12.8  -2.7   5.8   6.1   5.4
   6.5   4.3   6.4   8.9   9.3   9.7  11.4   9.9   5.5   6.    7.6   6.8
   4.8   6.2   7.9  10.1  10.    5.7  10.3   6.7  10.2  12.1  12.7  11.7
  11.5  11.6  11.3  10.5  -2.6   5.9   9.    9.5  10.9  10.7   9.1   7.4
   8.3  10.6  10.8  12.3  12.4  11.8   8.7   9.2   8.4   6.6   7.5   5.1
   4.9   4.1   8.1   9.8   8.8   7.7  10.4  11.9  14.1  17.3  20.   21.7
  22.2  22.7  21.8  18.4  17.1  12.8  13.4  12.6  11.2  13.9  15.6  17.8
  19.8  18.5  17.   16.3  16.6  15.9  12.5   7.2   7.1   8.   14.9  16.5
  21.5  22.5  23.3  22.   19.7  17.5  18.1  16.   14.2  14.3  14.   13.8
  18.2  20.2  22.3  23.8  24.7  25.4  25.5  25.2  20.7  17.2  16.4  18.
  15.5  15.   11.   13.2  13.7  15.4  19.6  20.4  23.   22.8  21.4  16.7
  15.1  14.5  16.2  16.8  14.7   7.3   4.7   6.3   4.5   8.2   7.    6.9
   7.8   5.6   8.5   8.6   9.4  12.2  13.5  16.1  13.6  15.3  14.8  12.
  12.9  13.1  19.4  14.6  15.7  14.4  15.2  19.3  24.9  24.1  24.8  26.6
  27.4  27.8  27.3  26.7  26.4  20.5  19.5  19.   18.9  17.4  11.1  15.8
  18.7   9.6  13.   13.3  16.9  20.1  20.6  20.9  21.   19.9  19.2  17.6
  17.9  18.6  22.4  23.9  23.6  18.8  21.2  21.9  23.2  23.4  23.5  22.9
  18.3  20.3  20.8  17.7  19.1  25.6  25.8  26.   24.3  21.6  26.8  28.6
  29.5  30.9  31.2  30.8  29.2  26.9  25.9  24.   28.   28.4  28.8  28.9
  28.2  27.7  26.5  21.1  24.6  26.1  27.1  27.6  28.1  24.4  23.1  27.2
  26.2  21.3  22.1  22.6  24.2  23.7  25.3  28.7  29.4  30.1  29.6  29.1
  25.   24.5  25.7  27.   27.9  26.3  28.5  29.7  31.7  32.2  32.3  32.4
  30.6  25.1  31.8  31.6  32.6  33.   32.5  32.1  31.1  30.3  27.5  29.
  29.8  30.7  30.2  29.9  28.3  30.5  30.4  31.9  31.4  32.7  32.9  31.5
  29.3  30.   32.   32.8  -9.1]
Dew Point Temp_C : [ -3.9  -3.7  -3.4  -3.2  -3.3  -3.1  -3.6  -2.3  -2.1  -2.   -1.7  -1.1
  -0.4  -0.2   0.    1.    1.3   1.7   1.9   2.    1.5  -0.9  -1.5  -2.6
  -2.9  -4.1  -3.5  -6.2  -6.5  -6.8  -7.   -8.7  -9.5 -11.4 -12.1 -13.4
 -12.8 -14.7 -14.1 -16.  -17.2 -15.8 -18.7 -20.1 -19.1 -19.3 -19.5 -21.3
 -21.9 -22.2 -22.6 -22.4 -22.9 -23.2 -23.8 -24.8 -25.4 -24.6 -24.2 -24.1
 -24.  -22.5 -20.6 -21.1 -21.7 -19.  -16.3 -15.5 -13.2 -12.6 -12.7 -11.6
 -11.7 -10.2  -8.3  -7.7 -10.7  -9.7  -9.1 -10.1 -10.   -9.6 -12.  -14.4
 -15.4 -15.7 -14.8 -16.8 -17.3 -16.5 -16.1 -16.2 -16.7 -15.6 -14.3 -13.6
 -13.  -12.5 -12.2 -11.1 -10.8 -10.5  -9.   -8.   -7.8  -7.2  -6.9  -6.1
  -5.9  -5.4  -5.3  -5.   -3.   -4.6  -9.2 -10.3 -11.9 -12.4 -12.9 -13.3
 -13.8 -13.9 -13.7 -14.  -14.5 -11.   -6.6  -5.8  -5.1  -5.7  -5.6  -6.3
  -5.2  -2.5  -1.2  -0.7  -0.8  -7.9 -10.9 -17.8 -18.9 -19.4 -21.  -21.4
 -20.8 -20.9 -20.4 -20.  -19.9 -19.2 -18.1 -15.2 -15.  -13.1 -11.3  -8.9
  -8.6  -8.5  -7.6  -7.3  -8.1  -7.5  -7.4  -6.   -4.8  -4.5 -11.2 -19.8
 -23.5 -23.6 -23.9 -23.4 -24.3 -24.4 -25.8 -25.9 -26.  -26.2 -26.8 -26.6
 -26.1 -26.5 -28.5 -28.  -27.8 -25.5 -22.8 -22.7 -23.  -23.3 -21.5 -20.7
 -17.7 -16.9 -17.5 -18.3 -17.1 -14.6 -10.4  -9.9  -4.9   0.7  -4.   -8.2
 -16.6 -17.6 -18.  -18.4 -18.8 -18.2 -17.4 -21.6 -19.7 -14.9  -8.4  -9.3
 -20.3 -21.2 -22.1 -23.7 -25.6 -25.1 -24.5 -21.8 -22.  -20.2 -17.   -2.4
  -0.3   1.2   1.4   2.2   2.5   2.3   2.1   3.6  -0.6  -1.8  -1.9  -2.2
  -2.8 -11.8 -11.5 -13.5  -8.8  -4.2  -1.4  -1.   -1.3  -1.6  -2.7  -4.4
  -4.3 -15.1 -14.2 -15.3 -15.9 -12.3  -7.1  -6.7  -6.4 -17.9 -18.6  -4.7
  -3.8 -16.4  -5.5 -23.1 -25.3 -19.6 -10.6   0.1   0.2   0.3  -0.5   1.1
   1.6   0.9  -9.8   0.4  -9.4 -18.5 -22.3 -20.5   0.8   2.9   3.8   4.
   5.2   5.9   6.6   6.4   6.9   7.8   3.2   0.6   1.8   3.    4.5   3.3
   2.8  -0.1   0.5   3.5   3.7   3.4   2.7   2.6   5.3   6.2   4.3   4.4
   4.1   4.7   5.4   5.5   4.9   2.4   5.8   6.7   7.6   8.7   9.9  10.5
  10.4  10.7  11.   10.1   9.8   8.6   9.2   8.9   7.9   8.5   8.3   9.
   8.1   9.4  11.6  12.   10.    9.7   9.1  10.8  11.8  12.3  12.1  11.7
  10.9  10.3   8.8  11.5  12.5  12.6   9.5   7.4   8.4  11.4  11.9  12.8
  12.2   6.8   7.2   7.1   7.5   6.5   6.3   4.6   4.8   5.7   3.1   8.
  10.6  11.2  11.1  13.3  13.5  13.6  12.4  11.3  15.6  15.8  14.7  14.2
   9.6   6.1   3.9   4.2   5.1   5.6   7.    8.2   7.7   7.3  10.2  13.
  12.9   9.3   5.    6.   12.7  13.1  13.8  13.9  14.5  15.   14.3  14.6
  14.4  15.2  15.4  15.3  15.1  14.   13.2  14.1  13.4  16.   16.2  16.4
  16.1  16.5  16.9  16.3  17.3  16.7  15.9  17.   17.7  17.5  15.5  15.7
  16.8  17.2  17.1  18.3  18.5  18.1  14.8  18.7  18.4  19.   17.4  17.6
  17.8  17.9  13.7  18.   16.6  14.9  18.9  19.2  19.4  19.1  19.3  18.8
  18.2  19.8  20.   20.4  19.6  20.3  19.9  21.1  21.   20.2  20.1  18.6
  20.8  20.6  20.7  19.7  20.9  21.2  21.7  21.9  20.5  19.5  21.3  22.3
  23.1  22.   22.2  22.6  23.2  23.   22.9  24.4  21.8]
Rel Hum_% : [ 86  87  89  88  85  91  82  81  84  79  77  72  71  69  70  68  67  66
  56  57  59  55  54  58  65  53  60  61  63  52  50  49  62  51  75  73
  80  83  76  64  74  78  47  90  48  45  46  92  93  42  43  40  39  44
  94  37  41  38  96  98  99  97  95 100  29  28  27  19  20  18  25  26
  30  24  34  33  31  32  35  36  21  22  23]
Wind Speed_km/h : [ 4  7  6  9 15 13 20 22 19 24 30 35 39 32 33 26 44 43 48 37 28 17 11  0
 83 70 57 46 41 52 50 63 54  2]
Visibility_km : [ 8.   4.   4.8  6.4  1.2 12.9 16.1 25.  19.3 24.1  9.7 11.3 48.3  3.2
  2.8  2.4  2.   0.8  0.6  1.   1.6  3.6  0.2  0.4]
Press_kPa : [101.24 101.26 101.27 101.23 101.29 101.2  101.15 100.98 100.79 100.58
 100.31 100.07  99.93  99.81  99.74  99.68  99.5   99.39  99.32  99.31
  99.26  99.3   99.21  99.18  99.14  99.19  99.27  99.33  99.41  99.66
  99.86 100.   100.15 100.26 100.27 100.35 100.43 100.53 100.61 100.68
 100.76 100.85 100.95 101.07 101.33 101.34 101.38 101.44 101.51 101.58
 101.64 101.74 101.82 101.86 101.87 101.88 101.89 101.77 101.75 101.73
 101.68 101.54 101.41 101.25 100.97 100.89 100.69 100.65 100.54 100.5
 100.42 100.32 100.29 100.28 100.24 100.21 100.19 100.39 100.45 100.41
 100.38 100.4  100.46 100.52 100.6  100.71 100.8  100.83 100.81 100.84
 100.7  100.51 100.47 100.36 100.23 100.13 100.06 100.1  100.12 100.16
 100.11 100.08 100.05 100.09 100.33 100.48 100.62 100.72 101.13 101.21
 101.47 101.59 101.7  101.81 101.92 101.9  101.94 101.97 102.04 102.09
 102.17 102.23 102.26 102.28 102.22 102.13 102.15 102.11 102.02 101.93
 101.8  101.4  101.05 100.96 100.9  100.77 100.64 100.02 100.04 100.91
 101.04 101.32 101.43 101.49 101.57 101.66 101.72 101.78 101.63 101.56
 101.61 101.6  101.19 101.17 101.08 101.02 100.93 100.22  99.97  99.9
  99.88  99.83  99.76  99.72  99.64  99.56  99.47  99.4   99.24  99.22
  99.13  99.06  98.94  98.84  98.69  98.56  98.44  98.22  98.07  97.99
  98.1   98.16  98.23  98.32  98.6   98.89  99.09  99.28  99.51  99.67
  99.85 100.01 100.73 101.14 101.16 101.18 101.3  101.36 101.46 101.62
 101.65 101.79 101.99 102.12 102.19 102.37 102.45 102.57 102.66 102.68
 102.67 102.65 102.71 102.79 102.85 102.89 102.94 102.98 103.02 103.07
 103.09 103.05 103.08 103.01 102.96 102.9  102.75 102.62 102.44 101.71
 101.31 101.12 100.94 100.88 100.75 100.59  99.69  99.57  99.38  98.98
  98.71  98.47  98.31  98.36  98.62  99.    99.36  99.7  100.78 100.92
 101.   101.09 101.45 101.67 101.83 101.85 101.84 101.42 101.22 101.03
 100.66 100.63 100.87 101.96 101.98 102.21 102.27 102.33 102.34 102.36
 102.29 102.18 102.08 102.06 102.03 102.01 102.16 102.24 102.47 102.52
 102.54 102.64 102.84 102.91 103.04 102.97 102.86 102.74 102.6  102.38
 102.14 102.1  101.76 101.69 101.01 100.86 100.25 100.37 100.49 100.82
 101.06 101.11 101.37 101.52 102.05 102.07 101.95 101.53 101.28 100.99
  99.98  99.8   99.61  99.34  99.08  98.91  98.76  98.65  98.74  98.97
  99.54  99.75 100.03 100.34 100.74 100.14  99.95  99.87  99.96 100.67
 101.55 100.56 102.31 102.35 102.39 102.4  102.42 102.51 102.59 102.61
 102.46 102.25 102.32 101.91 101.48 100.57 101.39 102.2  101.1  100.55
 100.3  100.44 102.   101.5  100.2   99.77  99.59  99.52  99.29  99.23
  99.17  99.11  99.16  99.2   99.42  99.49  99.53  99.6   99.82  99.91
  99.07  98.88  98.81  98.55  98.39  98.29  98.18  98.06  98.    97.97
  98.03  98.11  98.2   98.33  98.45  98.75  99.05 102.41 102.49 102.55
 102.63 102.72 102.58 102.5  102.69 102.53 102.56 102.3   99.55  99.02
  98.79  98.7   98.86  98.82  98.73  98.68  98.67  98.92  98.96  99.46
  99.63  99.84  99.94 100.18 102.7  103.   103.06 103.1  103.12 102.81
  99.99  99.78 102.73 102.95 102.99 101.35 100.17 102.48 102.43  99.45
  99.48  99.92  99.89  99.71  99.12  99.1   99.43  99.37  99.58  99.15
  98.9   98.8   98.66  98.61  98.54  98.51  98.58  98.64  98.5   98.53
  98.63  98.72  98.78  99.01  99.79  99.65  99.62  99.73  99.44  99.35
  99.25 103.15 103.25 103.29 103.31 103.34 103.2  103.16 103.17 103.18
 102.93 103.13 103.24 103.28 103.39 103.47 103.51 103.52 103.5  103.43
 103.46 103.49 103.54 103.56 103.58 103.59 103.63 103.61 103.65 103.38
 103.36 103.3  103.27 103.22 103.11 103.03 102.92 102.83 102.78 102.82
 103.14 103.26 103.21 103.19 103.23  97.93  97.76  97.56  97.52  97.58
  97.64  97.75  97.79  97.81  97.84  97.89  97.98  98.19]
Weather : ['Fog' 'Freezing Drizzle,Fog' 'Mostly Cloudy' 'Cloudy' 'Rain'
 'Rain Showers' 'Mainly Clear' 'Snow Showers' 'Snow' 'Clear'
 'Freezing Rain,Fog' 'Freezing Rain' 'Freezing Drizzle' 'Rain,Snow'
 'Moderate Snow' 'Freezing Drizzle,Snow' 'Freezing Rain,Snow Grains'
 'Snow,Blowing Snow' 'Freezing Fog' 'Haze' 'Rain,Fog' 'Drizzle,Fog'
 'Drizzle' 'Freezing Drizzle,Haze' 'Freezing Rain,Haze' 'Snow,Haze'
 'Snow,Fog' 'Snow,Ice Pellets' 'Rain,Haze' 'Thunderstorms,Rain'
 'Thunderstorms,Rain Showers' 'Thunderstorms,Heavy Rain Showers'
 'Thunderstorms,Rain Showers,Fog' 'Thunderstorms' 'Thunderstorms,Rain,Fog'
 'Thunderstorms,Moderate Rain Showers,Fog' 'Rain Showers,Fog'
 'Rain Showers,Snow Showers' 'Snow Pellets' 'Rain,Snow,Fog'
 'Moderate Rain,Fog' 'Freezing Rain,Ice Pellets,Fog'
 'Drizzle,Ice Pellets,Fog' 'Drizzle,Snow' 'Rain,Ice Pellets'
 'Drizzle,Snow,Fog' 'Rain,Snow Grains' 'Rain,Snow,Ice Pellets'
 'Snow Showers,Fog' 'Moderate Snow,Blowing Snow']

#### 2)Print Column Name & and how many values ​​are there in it

In [54]:
weather.nunique().reset_index()

              index     0
0         Date/Time  8784
1            Temp_C   533
2  Dew Point Temp_C   489
3         Rel Hum_%    83
4   Wind Speed_km/h    34
5     Visibility_km    24
6         Press_kPa   518
7           Weather    50

#### 3)find all the unique "Wind Speed" values in the dataset.

In [55]:
np.unique(weather["Wind Speed_km/h"].values)

array([ 0,  2,  4,  6,  7,  9, 11, 13, 15, 17, 19, 20, 22, 24, 26, 28, 30,
       32, 33, 35, 37, 39, 41, 43, 44, 46, 48, 50, 52, 54, 57, 63, 70, 83])

#### 4)find the number of times when the weather is exactly clear

In [56]:
weather.sample()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
1885,3/19/2012 13:00,18.5,11.0,62,19,19.3,101.72,Mainly Clear

In [57]:
weather[weather["Weather"]=="Clear"]["Weather"].count().item()

1326

#### 5)Find the number of times when the wind speed was exactly 4km/h

In [58]:
weather[weather["Wind Speed_km/h"]==4]["Wind Speed_km/h"].count().item()

474

#### 6)what is the mean max min value of each column against each weather condition

In [59]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [60]:
weather["Date/Time"] = pd.to_datetime(weather["Date/Time"], errors = "coerce" )

In [61]:
weather.groupby("Weather").agg(["mean", "min", "max"]).head()

                                            Date/Time                      \
                                                 mean                 min
Weather
Clear                   2012-06-25 18:03:12.760180992 2012-01-03 19:00:00
Cloudy                  2012-07-01 16:51:29.583333376 2012-01-01 17:00:00
Drizzle                 2012-09-17 15:00:00.000000000 2012-01-23 21:00:00
Drizzle,Fog             2012-06-30 00:44:15.000000000 2012-01-23 20:00:00
Drizzle,Ice Pellets,Fog 2012-12-17 09:00:00.000000000 2012-12-17 09:00:00

                                               Temp_C              \
                                        max      mean   min   max
Weather
Clear                   2012-12-30 20:00:00  6.825716 -23.3  32.8
Cloudy                  2012-12-31 06:00:00  7.970544 -21.4  30.5
Drizzle                 2012-12-22 01:00:00  7.353659   1.1  18.8
Drizzle,Fog             2012-12-19 10:00:00  8.067500   0.0  19.9
Drizzle,Ice Pellets,Fog 2012-12-17 09:00:00  0.400000   0.4   0.4

                        Dew Point Temp_C              Rel Hum_%           \
                                    mean   min   max       mean min  max
Weather
Clear                           0.089367 -28.5  20.4  64.497738  20   99
Cloudy                          2.375810 -26.8  22.6  69.592593  18   99
Drizzle                         5.504878  -0.2  17.7  88.243902  74   96
Drizzle,Fog                     7.033750  -1.6  19.1  93.275000  85  100
Drizzle,Ice Pellets,Fog        -0.700000  -0.7  -0.7  92.000000  92   92

                        Wind Speed_km/h         Visibility_km              \
                                   mean min max          mean   min   max
Weather
Clear                         10.557315   0  33     30.153243  11.3  48.3
Cloudy                        16.127315   0  54     26.625752  11.3  48.3
Drizzle                       16.097561   0  30     17.931707   6.4  25.0
Drizzle,Fog                   11.862500   0  28      5.257500   1.0   9.7
Drizzle,Ice Pellets,Fog       20.000000  20  20      4.000000   4.0   4.0

                          Press_kPa
                               mean     min     max
Weather
Clear                    101.587443   99.52  103.63
Cloudy                   100.911441   98.39  103.65
Drizzle                  100.435366   97.84  101.56
Drizzle,Fog              100.786625   98.65  102.07
Drizzle,Ice Pellets,Fog  100.790000  100.79  100.79

### Q-3)Blow questions are based on this data(Netflix Userbase):-

In [62]:
netflix = pd.read_csv("Netflix Userbase.csv")

In [63]:
netflix

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month
...,...,...,...,...,...,...,...,...,...,...
2495,2496,Premium,14,25-07-22,12-07-23,Spain,28,Female,Smart TV,1 Month
2496,2497,Basic,15,04-08-22,14-07-23,Spain,33,Female,Smart TV,1 Month
2497,2498,Standard,12,09-08-22,15-07-23,United States,38,Male,Laptop,1 Month
2498,2499,Standard,13,12-08-22,12-07-23,Canada,48,Female,Tablet,1 Month
2499,2500,Basic,15,13-08-22,12-07-23,United States,35,Female,Smart TV,1 Month

#### 1)Which subscription type contributes the highest share of total revenue, and how does this vary by country?

In [64]:
revenue = netflix.groupby("Subscription Type")["Monthly Revenue"].sum().reset_index()
revenue

  Subscription Type  Monthly Revenue
0             Basic            12469
1           Premium             9229
2          Standard             9573

In [65]:
netflix.groupby(["Country","Subscription Type"])["Monthly Revenue"].sum().reset_index().sort_values(by = "Monthly Revenue",ascending = False).drop_duplicates(keep = "first",subset = "Country")

           Country Subscription Type  Monthly Revenue
20           Spain           Premium             2689
24   United States             Basic             2483
23  United Kingdom          Standard             2283
14           Italy             Basic             2223
18          Mexico          Standard             2191
10          France           Premium             1862
11         Germany             Basic             1833
3           Brazil             Basic             1824
6           Canada             Basic             1816
1        Australia           Premium             1254

#### 2)Based on the gap between Join Date and Last Payment Date, what is the average retention period for each subscription type?

In [66]:
netflix["Join Date"] = pd.to_datetime(netflix["Join Date"], errors = "coerce", format = "%d-%m-%y")

In [67]:
netflix["Last Payment Date"] = pd.to_datetime(netflix["Last Payment Date"], errors = "coerce", format = "%d-%m-%y")

In [68]:
netflix["retention period_months"] = (netflix["Last Payment Date"] - netflix["Join Date"]).dt.days//30

In [69]:
avg_retention = round(netflix.groupby("Subscription Type")["retention period_months"].mean(),2).reset_index()
avg_retention

  Subscription Type  retention period_months
0             Basic                     9.77
1           Premium                     9.79
2          Standard                     9.90

#### 3)What is the average customer lifetime value (CLV) across subscription types, considering join and last payment dates?
CLV=Retention Period×Average Revenue per Month (or per Purchase)

In [70]:
netflix.sample()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,retention period_months
955,956,Premium,10,2022-06-24,2023-07-01,United States,42,Female,Smart TV,1 Month,12

In [71]:
netflix["CLV"] = netflix["Monthly Revenue"]*netflix["retention period_months"]

In [72]:
netflix.sample(3)

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,retention period_months,CLV
1094,1095,Basic,10,2022-06-24,2023-07-03,Germany,36,Male,Smartphone,1 Month,12,120
834,835,Premium,12,2022-09-27,2023-06-29,United States,31,Male,Laptop,1 Month,9,108
425,426,Premium,15,2022-10-05,2023-06-30,France,35,Male,Laptop,1 Month,8,120

#### 4)Which country has the highest churn rate (shortest average subscription duration)?

In [73]:
netflix.groupby("Country")["retention period_months"].mean().sort_values().tail(1)

Country
France    10.289617
Name: retention period_months, dtype: float64

#### 5)How does age distribution differ between Basic, Standard, and Premium subscribers?

In [74]:
def age_grp(x):
    if x<=20:
        return "less than 20"
    elif x>20 and x<=30:
        return "21-30"
    elif x>30 and x<=40:
        return "31-40"
    else:
        return "greater than 40"

In [75]:
netflix["age group"] = netflix["Age"].apply(age_grp)

In [76]:
netflix.sample(5)

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration,retention period_months,CLV,age group
1504,1505,Basic,12,2022-06-30,2023-07-05,Italy,30,Male,Laptop,1 Month,12,144,21-30
409,410,Basic,15,2022-09-02,2023-06-25,Italy,37,Male,Smart TV,1 Month,9,135,31-40
837,838,Standard,11,2022-10-07,2023-07-02,United Kingdom,38,Male,Smartphone,1 Month,8,88,31-40
326,327,Basic,12,2022-07-06,2023-06-26,Brazil,32,Female,Smartphone,1 Month,11,132,31-40
2468,2469,Premium,12,2022-10-24,2023-07-11,Canada,36,Male,Laptop,1 Month,8,96,31-40

In [79]:
users = netflix.groupby(["Subscription Type", "age group"])["User ID"].count().reset_index()
users.rename(columns = {"User ID" : "user count"}).sort_values(by= ["Subscription Type", "user count"], ascending = [True, False])

  Subscription Type        age group  user count
2             Basic  greater than 40         422
1             Basic            31-40         406
0             Basic            21-30         171
5           Premium  greater than 40         309
4           Premium            31-40         289
3           Premium            21-30         135
8          Standard  greater than 40         339
7          Standard            31-40         312
6          Standard            21-30         117

#### 6)Is there a significant gender preference for certain subscription types or devices?

In [95]:
gender = netflix.groupby(["Subscription Type", "Device","Gender"])["User ID"].count().reset_index()
gender.rename(columns = {"User ID": "number of users"}, inplace = True)
result = gender.sort_values(by =  "number of users", ascending = False).drop_duplicates(subset = ["Subscription Type", "Device"])
result.sort_values(by = "Subscription Type")

   Subscription Type      Device  Gender  number of users
0              Basic      Laptop  Female              136
6              Basic      Tablet  Female              132
5              Basic  Smartphone    Male              127
2              Basic    Smart TV  Female              120
8            Premium      Laptop  Female              102
15           Premium      Tablet    Male               97
10           Premium    Smart TV  Female               95
13           Premium  Smartphone    Male               89
22          Standard      Tablet  Female              106
21          Standard  Smartphone    Male              105
17          Standard      Laptop    Male               94
19          Standard    Smart TV    Male               94

#### 7)Which device type contributes the highest total revenue globally?

In [98]:
netflix.groupby("Device")["Monthly Revenue"].sum().sort_values(ascending = False).reset_index()

       Device  Monthly Revenue
0      Laptop             7994
1      Tablet             7971
2  Smartphone             7691
3    Smart TV             7615

#### 8)Is there a correlation between device used and age group?

In [111]:
device = netflix.groupby(["Device","age group"])["User ID"].count().reset_index()
device.rename(columns = {"User ID": "number of users"}, inplace = True)
device.sort_values(by= ["Device", "number of users"], ascending = [True, False])

        Device        age group  number of users
2       Laptop  greater than 40              289
1       Laptop            31-40              248
0       Laptop            21-30               99
5     Smart TV  greater than 40              252
4     Smart TV            31-40              250
3     Smart TV            21-30              108
7   Smartphone            31-40              260
8   Smartphone  greater than 40              259
6   Smartphone            21-30              102
11      Tablet  greater than 40              270
10      Tablet            31-40              249
9       Tablet            21-30              114

#### 9)Which top 3 countries generate the most monthly revenue, and how is it split by subscription type?

In [118]:
netflix.groupby("Country")["Monthly Revenue"].sum().sort_values(ascending = False).head(3).reset_index()

         Country  Monthly Revenue
0  United States             5664
1          Spain             5662
2         Canada             3950

In [121]:
top = netflix[netflix["Country"].isin(["United States","Spain", "Canada"])]

In [123]:
top.groupby(["Country","Subscription Type"])["Monthly Revenue"].sum().reset_index()

         Country Subscription Type  Monthly Revenue
0         Canada             Basic             1816
1         Canada           Premium             1086
2         Canada          Standard             1048
3          Spain             Basic             1386
4          Spain           Premium             2689
5          Spain          Standard             1587
6  United States             Basic             2483
7  United States           Premium             1837
8  United States          Standard             1344