In [1]:
import pandas as pd
import numpy as np

In [2]:
rides = pd.read_csv("ncr_ride_bookings.csv", parse_dates = ["Date"])

In [3]:
rides.sample(2)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
134033,2024-06-03,17:22:44,"""CNR1554852""",Cancelled by Customer,"""CID9377413""",Go Mini,Keshav Puram,Udyog Vihar,5.4,NaN,...,Driver is not moving towards pickup location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16442,2024-04-30,09:33:12,"""CNR2952060""",Incomplete,"""CID2569213""",Premier Sedan,Okhla,Moti Nagar,9.4,16.2,...,NaN,NaN,NaN,1.0,Other Issue,421.0,10.85,NaN,NaN,UPI

#### 1)Convert Date and Time to datetime

In [4]:
rides["Date"].dtype # we had converted the date col to date col to datetime dtype at time of reading csv file

dtype('<M8[ns]')

In [5]:
rides["Time"] = pd.to_datetime(rides["Time"], errors = "coerce", format = "%H:%M:%S") 
## pandas add dummy date to time 1900-01-01 hh:mm:ss
# if we don't want this dummy date then do this:
# pd.to_datetime(rides["Time"], errors = "coerce", format = "%H:%M:%S").dt.time .
# However, this will be python datetime obj and will be of "object type".

In [6]:
rides["Time"].dtype

dtype('<M8[ns]')

In [7]:
rides.sample()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
127879,2024-06-04,1900-01-01 10:19:13,"""CNR2480524""",Completed,"""CID7897530""",Auto,Chhatarpur,Jhilmil,5.5,23.4,...,NaN,NaN,NaN,NaN,NaN,679.0,19.41,4.4,3.6,Uber Wallet

#### 2)Combine Date and Time into a single datetime column
##### method 1:

Since our "Date" and "Time" are both datetime, we can’t directly add them.
But if we convert each to string in the right format using .dt.strftime(),
then concatenate, then parse back → we get a clean datetime column:

##### method 2:
we could also combine these two cols durind reading the file time only using parde_date = [" "] and get datetime type col

##### some situation:

if: 

"Date" is datetime64[ns]

"Time" (after pd.to_datetime(rides["Time"], errors = "coerce", format = "%H:%M:%S").dt.time .) is Python datetime.time objects (object dtype)

Pandas can’t directly add those two.

solution: 

rides["Date Time"] = pd.to_datetime( rides["Date"].astype(str) + " " + rides["Time"].astype(str),errors="coerce")

In [8]:
#method 1:

rides["Date Time"] = pd.to_datetime(rides["Date"].dt.strftime("%Y-%m-%d")+" "+ rides["Time"].dt.strftime("%H-%M-%S"), format = "%Y-%m-%d %H-%M-%S",errors = "coerce")

In [9]:
rides["Date Time"].dtype

dtype('<M8[ns]')

In [10]:
rides.sample(3)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Date Time
74111,2024-08-14,1900-01-01 12:00:48,"""CNR6006614""",Completed,"""CID6708761""",Go Sedan,Sarojini Nagar,Rohini,14.2,35.0,...,NaN,NaN,NaN,NaN,801.0,25.68,4.5,4.6,UPI,2024-08-14 12:00:48
44495,2024-09-14,1900-01-01 16:27:08,"""CNR9249883""",No Driver Found,"""CID8982220""",Go Sedan,Udyog Bhawan,Shivaji Park,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-14 16:27:08
131253,2024-05-21,1900-01-01 21:12:11,"""CNR2285776""",Incomplete,"""CID7501409""",Go Sedan,Azadpur,Bhiwadi,4.9,20.2,...,NaN,NaN,1.0,Customer Demand,325.0,18.87,NaN,NaN,UPI,2024-05-21 21:12:11

In [88]:
#method 2:
#will be deprecated in future . so use above method
rides2 = pd.read_csv("ncr_ride_bookings.csv", parse_dates = {"DateTime" : ["Date","Time"]})

C:\Users\Hp\AppData\Local\Temp\ipykernel_11764\1027789386.py:3: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  rides2 = pd.read_csv("ncr_ride_bookings.csv", parse_dates = {"DateTime" : ["Date","Time"]})

In [89]:
rides2

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23 12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29 18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23 08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21 17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16 22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11 19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,NaN,NaN,NaN,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24 15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,NaN,NaN,NaN,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18 10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,NaN,NaN,NaN,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05 07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,NaN,NaN,NaN,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI
149999,2024-03-10 15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,NaN,NaN,NaN,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card

#### 3)Extract temporal features

In [90]:
rides["Date Time"].dt.year

0         2024
1         2024
2         2024
3         2024
4         2024
          ...
149995    2024
149996    2024
149997    2024
149998    2024
149999    2024
Name: Date Time, Length: 150000, dtype: int32

In [91]:
rides["Date Time"].dt.month

0          3
1         11
2          8
3         10
4          9
          ..
149995    11
149996    11
149997     9
149998    10
149999     3
Name: Date Time, Length: 150000, dtype: int32

In [92]:
rides["Date Time"].dt.day

0         23
1         29
2         23
3         21
4         16
          ..
149995    11
149996    24
149997    18
149998     5
149999    10
Name: Date Time, Length: 150000, dtype: int32

In [93]:
rides["Date Time"].dt.day_name()

0          Saturday
1            Friday
2            Friday
3            Monday
4            Monday
            ...
149995       Monday
149996       Sunday
149997    Wednesday
149998     Saturday
149999       Sunday
Name: Date Time, Length: 150000, dtype: object

In [94]:
rides["Date Time"].dt.month_name()

0             March
1          November
2            August
3           October
4         September
            ...
149995     November
149996     November
149997    September
149998      October
149999        March
Name: Date Time, Length: 150000, dtype: object

In [95]:
rides["Date Time"].dt.hour

0         12
1         18
2          8
3         17
4         22
          ..
149995    19
149996    15
149997    10
149998     7
149999    15
Name: Date Time, Length: 150000, dtype: int32

In [96]:
rides["Date Time"].dt.minute

0         29
1          1
2         56
3         17
4          8
          ..
149995    34
149996    55
149997    55
149998    53
149999    38
Name: Date Time, Length: 150000, dtype: int32

In [97]:
rides["Date Time"].dt.second

0         38
1         39
2         10
3         25
4          0
          ..
149995     1
149996     9
149997    15
149998    34
149999     3
Name: Date Time, Length: 150000, dtype: int32

In [98]:
rides["Date Time"].dt.day_of_week

0         5
1         4
2         4
3         0
4         0
         ..
149995    0
149996    6
149997    2
149998    5
149999    6
Name: Date Time, Length: 150000, dtype: int32

#### # 4)Create binary flags from cancellation/incomplete columns

In [99]:

pd.set_option("display.max_column",None)
rides2.sample(3)

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
67011,2024-04-02 21:28:16,"""CNR8423108""",Cancelled by Driver,"""CID5606611""",Bike,Lajpat Nagar,Mundka,7.8,NaN,NaN,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115882,2024-08-06 11:17:17,"""CNR3440856""",Cancelled by Driver,"""CID6890475""",Go Sedan,Sohna Road,Udyog Vihar,4.1,NaN,NaN,NaN,1.0,The customer was coughing/sick,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128462,2024-10-10 21:33:33,"""CNR5018901""",Completed,"""CID8540871""",Go Mini,Uttam Nagar,New Colony,14.9,24.2,NaN,NaN,NaN,NaN,NaN,NaN,263.0,43.66,3.4,4.1,UPI

In [100]:
rides2["cancellation_flag"] = np.where((rides2["Cancelled Rides by Customer"].notna() ) | (rides2["Cancelled Rides by Driver"].notna() ),1,0)

In [101]:
rides2["cancellation_flag"].value_counts()  ## 1: ride cancelled, 0 : not cancelled

cancellation_flag
0    112500
1     37500
Name: count, dtype: int64

In [102]:
rides2["customer_cancellation_flag"] = np.where(rides2["Cancelled Rides by Customer"].notna(),1,0)

In [103]:
rides2["customer_cancellation_flag"].value_counts()

customer_cancellation_flag
0    139500
1     10500
Name: count, dtype: int64

In [104]:
rides2["driver_cancellation_flag"] = np.where(rides2["Cancelled Rides by Driver"].notna(),1,0)

In [105]:
rides2["driver_cancellation_flag"].value_counts()

driver_cancellation_flag
0    123000
1     27000
Name: count, dtype: int64

In [106]:
rides2["incomplete_flag"] = np.where(rides2["Incomplete Rides"].notna(), 1,0)

In [107]:
rides2["incomplete_flag"].value_counts()

incomplete_flag
0    141000
1      9000
Name: count, dtype: int64

#### 5)Create a flag for missing ratings and booking values

In [108]:
rides2.sample(3)

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag
121551,2024-07-30 08:06:12,"""CNR4931218""",Completed,"""CID9014414""",Premier Sedan,Vaishali,Sonipat,11.6,20.0,NaN,NaN,NaN,NaN,NaN,NaN,667.0,30.29,4.3,4.9,Cash,0,0,0,0
20075,2024-11-02 01:04:01,"""CNR7982564""",Completed,"""CID7018672""",Go Mini,IIT Delhi,Shivaji Park,9.9,35.8,NaN,NaN,NaN,NaN,NaN,NaN,397.0,19.32,4.0,4.9,Cash,0,0,0,0
87141,2024-01-23 14:39:00,"""CNR1715877""",Completed,"""CID7030947""",Go Mini,Udyog Bhawan,Punjabi Bagh,11.9,37.5,NaN,NaN,NaN,NaN,NaN,NaN,944.0,26.36,3.9,4.6,Cash,0,0,0,0

In [109]:
rides2["missing_ratings"] = np.where((rides2["Driver Ratings"].notna()) & (rides2["Customer Rating"].notna()),0,1)

In [110]:
rides2["driver_missing_ratings"]  = np.where(rides["Driver Ratings"].notna(),0,1)

In [111]:
rides2["customer_missing_ratings"]  = np.where(rides["Customer Rating"].notna(),0,1)

In [112]:
rides2.sample(3)

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag,missing_ratings,driver_missing_ratings,customer_missing_ratings
96184,2024-08-28 20:59:07,"""CNR3444982""",Completed,"""CID4348213""",Bike,Moolchand,Panipat,7.8,34.6,NaN,NaN,NaN,NaN,NaN,NaN,865.0,22.13,4.4,4.6,Cash,0,0,0,0,0,0,0
140800,2024-01-20 20:04:29,"""CNR7249560""",Completed,"""CID6306563""",Premier Sedan,Badshahpur,New Colony,9.5,35.2,NaN,NaN,NaN,NaN,NaN,NaN,92.0,18.99,4.3,4.3,Cash,0,0,0,0,0,0,0
35559,2024-05-12 08:18:27,"""CNR6377445""",Completed,"""CID2215339""",Auto,Inderlok,Azadpur,6.8,33.9,NaN,NaN,NaN,NaN,NaN,NaN,941.0,16.82,4.2,4.7,Cash,0,0,0,0,0,0,0

In [113]:
rides2["Booking Value"]  = np.where(rides["Booking Value"].notna(),0,1)

In [114]:
rides2["Booking Value"].value_counts()

Booking Value
0    102000
1     48000
Name: count, dtype: int64

#### 6)Define Target for Customer Cancellation

In [115]:
# we have already created the target which is customer cancellation flg
rides2["customer_cancellation_flag"].value_counts()

customer_cancellation_flag
0    139500
1     10500
Name: count, dtype: int64

#### 7)Cancellation Rate by Vehicle Type

In [116]:
# method 1
round((rides2.groupby("Vehicle Type")["cancellation_flag"].mean())*100,2).reset_index()

    Vehicle Type  cancellation_flag
0           Auto              24.92
1           Bike              25.10
2        Go Mini              24.92
3       Go Sedan              25.29
4  Premier Sedan              24.94
5        Uber XL              24.48
6          eBike              24.91

In [117]:
# method 2
round((rides2.groupby("Vehicle Type").agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

               cancellation_rate
Vehicle Type
Auto                       24.92
Bike                       25.10
Go Mini                    24.92
Go Sedan                   25.29
Premier Sedan              24.94
Uber XL                    24.48
eBike                      24.91

##### why use mean for cancellation rate: 
Suppose in the 10 AM group you have 5 rides:

Sum of flags = 1+0+0+1+0 = 2

Total rides = 5

Cancellation rate = 2/5 = 0.4 (40%)

Now check what mean gives:

mean=(1+0+0+1+0)/5=0.4

Same thing!

#### 8)Cancellation Rate by Hour

In [118]:
rides2.sample()

,DateTime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,cancellation_flag,customer_cancellation_flag,driver_cancellation_flag,incomplete_flag,missing_ratings,driver_missing_ratings,customer_missing_ratings
132395,2024-09-11 19:35:12,"""CNR2406802""",Completed,"""CID5242720""",Go Sedan,Ashram,Nawada,2.8,29.1,NaN,NaN,NaN,NaN,NaN,NaN,0,43.76,4.9,4.8,UPI,0,0,0,0,0,0,0

In [119]:
# rides2["hours"]=rides2["DateTime"].dt.hour

In [122]:
round((rides2.groupby(rides2["DateTime"].dt.hour).agg( cancellation_rate_by_hour = ("cancellation_flag" ,"mean")))*100,2)

          cancellation_rate_by_hour
DateTime
0                             24.76
1                             25.29
2                             22.18
3                             25.67
4                             25.59
5                             26.42
6                             24.16
7                             25.36
8                             24.98
9                             24.91
10                            24.90
11                            24.05
12                            24.74
13                            25.25
14                            26.08
15                            25.68
16                            24.52
17                            24.89
18                            25.38
19                            25.53
20                            24.59
21                            23.98
22                            25.57
23                            25.42

#### 9)Cancellation Rate by Day of Week

In [135]:
days = ["Monday","Tuesday","Wednesday","Thursday","Friday", "Saturday","Sunday"]
cancellation_by_day = round((rides2.groupby(rides2["DateTime"].dt.day_name()).agg(cancellation_rate_day = ("cancellation_flag" ,"mean")))*100,2)
cancellation_by_day.reindex(days)

           cancellation_rate_day
DateTime
Monday                     25.65
Tuesday                    25.19
Wednesday                  24.82
Thursday                   24.66
Friday                     24.97
Saturday                   24.73
Sunday                     24.97

#### 10)Driver Rating vs Cancellation

In [140]:
round((rides2.groupby(rides2["Driver Ratings"]).agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

                cancellation_rate
Driver Ratings
3.0                           0.0
3.1                           0.0
3.2                           0.0
3.3                           0.0
3.4                           0.0
3.5                           0.0
3.6                           0.0
3.7                           0.0
3.8                           0.0
3.9                           0.0
4.0                           0.0
4.1                           0.0
4.2                           0.0
4.3                           0.0
4.4                           0.0
4.5                           0.0
4.6                           0.0
4.7                           0.0
4.8                           0.0
4.9                           0.0
5.0                           0.0

In [146]:
# making bins of ratings
bins = [0,2,3,4,5]
labels = ["1-2","2-3","3-4","4-5"]
rides2["ratings"]=pd.cut(rides2["Driver Ratings"], bins = bins , labels = labels, include_lowest = True)

In [147]:
round((rides2.groupby(rides2["ratings"]).agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

C:\Users\Hp\AppData\Local\Temp\ipykernel_11764\3030147022.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  round((rides2.groupby(rides2["ratings"]).agg(cancellation_rate = ("cancellation_flag" ,"mean")))*100,2)

         cancellation_rate
ratings
1-2                    NaN
2-3                    0.0
3-4                    0.0
4-5                    0.0